Repository team-desire/hello-sketch-client, pull requests merged in 2023-08, with the labels that each got.

#19 [TASK-79] fix: Carousel을 Home에서 수정
  src/pages/Home/index.jsx
Labels: fix

#20 [TASK-50] feat: favicon 파일 추가
  index.html
  public/favicon.ico
Labels: feat

#23 [TASK-69] chore: 불필요한 import 제거
  src/main.jsx
Labels: fix

#27 [TASK-63] feat: 스케치 저장 후 mySketch 페이지로 이동 기능 추가
  src/components/CanvasContainer/index.jsx
Labels: refactor, feat

#29 [TASK-88] chore: 유닛 테스트 환경 구축
  package-lock.json
  package.json
  src/setupTests.js
  vite.config.js
Labels: chore
